# Error Handling

In [3]:
def devision():
    x = int(input("Please Enter A Number"))
    y = int(input("Please Enter Another Number"))
    return x / y

In [4]:
devision()

Please Enter A Number 5
Please Enter Another Number 5


1.0

In [6]:
devision()

Please Enter A Number 5
Please Enter Another Number 10


0.5

# Possible errors
- ValueError
- ZeroDivisionError

In [4]:
# error handling
def devision_v1():
    print("Welcome to division calculator")
    
    try:
        x = int(input("Please Enter A Number"))
        y = int(input("Please Enter Another Number"))
        result = x / y
        
    except ValueError as error_message:
        print("Invalid Input Format")
        print(error_message)
    
    except ZeroDivisionError as error_message:
        print("Can not provide 0 for deno")
        print(error_message)
    
    except Exception as error_message:
        print("Some Unknown Error")
        print(error_message)
    
    else:
        print("Successfully executed")
        return result
    
    finally:
        print("Done with the program")

In [5]:
a = devision_v1()

Welcome to division calculator
Please Enter A Number5
Please Enter Another Number6
Successfully executed
Done with the program


In [6]:
devision_v1()

Welcome to division calculator
Please Enter A Number5
Please Enter Another Number8
Successfully executed
Done with the program


0.625

# Problem

In [7]:
employees = {
    "John":123454,
    "Riya":315564,
    "Sam":54646,
    "ex_emp1":52454,
    "ex_emp2":546464
}

In [8]:
ex_employees = ["ex_emp1","ex_emp2"]

In [9]:
def calc_bonus(name, account_num):
    try:
        print("****************************************")
        if name in ex_employees:
            print("Can not process !!  Ex Employees")
        else:
            
            print("Input Details For {}".format(name))

            num_a = int(input("Number of Days Worked = "))
            num_b = int(input("Salary Acc Till Now = "))

            bonus = (num_b / num_a) * 10
            print("Bonus Awarded = Rs {}/-".format(bonus))
            print("NEFT BONUS TO ACCOUNT of {}".format(name))
        print("****************************************")
    
    except Exception as error_message:
        print(error_message)

In [10]:
for name, account in employees.items():
    calc_bonus(name, account)

****************************************
Input Details For John
Number of Days Worked = 55
Salary Acc Till Now = 55
Bonus Awarded = Rs 10.0/-
NEFT BONUS TO ACCOUNT of John
****************************************
****************************************
Input Details For Riya
Number of Days Worked = 55
Salary Acc Till Now = 55
Bonus Awarded = Rs 10.0/-
NEFT BONUS TO ACCOUNT of Riya
****************************************
****************************************
Input Details For Sam
Number of Days Worked = 55
Salary Acc Till Now = 55
Bonus Awarded = Rs 10.0/-
NEFT BONUS TO ACCOUNT of Sam
****************************************
****************************************
Can not process !!  Ex Employees
****************************************
****************************************
Can not process !!  Ex Employees
****************************************


In [11]:
def calc_bonus_v2(name, account_num):
    try:
        print("****************************************")
        if name in ex_employees:
            raise Exception("Emp Has Left The company")
        
        print("Input Details For {}".format(name))

        num_a = int(input("Number of Days Worked = "))
        num_b = int(input("Salary Acc Till Now = "))

        bonus = (num_b / num_a) * 10
        print("Bonus Awarded = Rs {}/-".format(bonus))
        print("NEFT BONUS TO ACCOUNT of {}".format(name))
        print("****************************************")
    
    except Exception as error_message:
        print(error_message)

In [12]:
for name, account in employees.items():
    calc_bonus_v2(name, account)

****************************************
Input Details For John
Number of Days Worked = 55
Salary Acc Till Now = 55
Bonus Awarded = Rs 10.0/-
NEFT BONUS TO ACCOUNT of John
****************************************
****************************************
Input Details For Riya
Number of Days Worked = 55
Salary Acc Till Now = 55
Bonus Awarded = Rs 10.0/-
NEFT BONUS TO ACCOUNT of Riya
****************************************
****************************************
Input Details For Sam
Number of Days Worked = 55
Salary Acc Till Now = 55
Bonus Awarded = Rs 10.0/-
NEFT BONUS TO ACCOUNT of Sam
****************************************
****************************************
Emp Has Left The company
****************************************
Emp Has Left The company


# REGEX

In [13]:
import re

In [14]:
# find - to find all occurances
# search - to check if something exists
# sub - to replace

In [15]:
txt = '''We teach Python at learnbay
Also there are classes for data science.
Our email id is asd@skd.com
sd65@gmail.com
sdf@sadkf.in sadfas
We also teach Numpy and Pandas
you can also write us at sad@ksjd.com
'''

In [16]:
re.search("We.*learnbay", txt, re.IGNORECASE)

<re.Match object; span=(0, 27), match='We teach Python at learnbay'>

In [17]:
re.search("@.*com", txt) # if there is a email id or not

<re.Match object; span=(88, 96), match='@skd.com'>

In [18]:
re.findall("@.*com", txt)

['@skd.com', '@gmail.com', '@ksjd.com']

In [19]:
txt = '''We teach Python at learnbay
Also there are classes for data science.
Our email id is asd@skd.com
sd65@gmail.com
sdf@sadkf.in sadfas
We also teach Numpy and Pandas
you can also write us at sad@ksjd.com

nishant_gautam@gmail.com
nishant-gautam@gmail.com

asdf.sadf@asdf.com
arun.kumar@company
'''

In [20]:
re.findall("[a-z0-9\_\.\-]+@.*[a-z]+",txt)

['asd@skd.com',
 'sd65@gmail.com',
 'sdf@sadkf.in sadfas',
 'sad@ksjd.com',
 'nishant_gautam@gmail.com',
 'nishant-gautam@gmail.com',
 'asdf.sadf@asdf.com',
 'arun.kumar@company']

# replace

In [21]:
data = 'good'
re.sub('oo', 'u', data)

'gud'

# Numpy

In [22]:
import numpy as np

In [23]:
# lists and tuple are very slow
# faster calculations

In [24]:
my_list = [5,55,558,'Nishant']
my_list

[5, 55, 558, 'Nishant']

In [25]:
sum(my_list)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

# 1d array

- nd array

In [26]:
my_first_array = np.array([1,2,3])
my_first_array

array([1, 2, 3])

In [27]:
my_first_array = np.array([1,'something',3])
my_first_array

array(['1', 'something', '3'], dtype='<U21')

In [28]:
my_first_array = np.array([1,True,3])
my_first_array

array([1, 1, 3])

In [10]:
np.zeros(55)

<IPython.core.display.Javascript object>

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.random.randint(1,10,3)

<IPython.core.display.Javascript object>

array([3, 6, 8])

# How to read documentaion

In [23]:
# np.lookfor('addition')

In [32]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArray.__new_

# Understand each of funcitons below and create an example

# np.linspace
# np.random.random
# np.eye
# np.full

# indexing and slicing

In [33]:
a = np.array([1,2,3,4])

In [34]:
a[2]

3

In [35]:
a[0:2]

array([1, 2])

In [36]:
b = np.random.random((3,4))
b

array([[0.50266157, 0.63198982, 0.54674363, 0.68827534],
       [0.5702461 , 0.91401936, 0.79805475, 0.70933193],
       [0.58510206, 0.99852814, 0.212448  , 0.29144745]])

```name_of_array[row_start:row_end,col_start:col_end]```

In [37]:
b[0:2,1:3] # slicing

array([[0.63198982, 0.54674363],
       [0.91401936, 0.79805475]])

In [38]:
b[0][2] # indexing

0.5467436275541823

In [39]:
b[:,0:2]

array([[0.50266157, 0.63198982],
       [0.5702461 , 0.91401936],
       [0.58510206, 0.99852814]])

# Problem

Play around with slicing by creating your own example

# Basics of Matrix