## For Exception

#### 1. Write a program to write something in a text file which is not existing . Handle the exception gracefully and write some content in file.

###### Do it on your own

## Numpy, Pandas and Matplotlib

#### 2. Write a program to generate an array of 30 numbers (1 to 30) of all possible shapes.

In [54]:
def findPossibleShapes(size):
    possible_shapes = []
    for i in range(1,size+1):
        for j in range(size,1,-1):
            if i*j == size:
                #print("Possible shapes are::",(i,j))
                if i != j:
                    possible_shapes.append((i,j))
                    possible_shapes.append((j,i))
                else:
                    possible_shapes.append((i,i))
                    
    return set(possible_shapes)

# print (findPossibleShapes(36))

import numpy as np
size = 36
a = np.arange(size)
for shape in findPossibleShapes(size):
    #print(shape)
    print("For shape::",shape)
    print(a.reshape(shape))
    print("#"*20)
    

For shape:: (3, 12)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]]
####################
For shape:: (4, 9)
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]
####################
For shape:: (18, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]]
####################
For shape:: (2, 18)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]]
####################
For shape:: (6, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
####################
For shape:: (1, 36)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35]]
###################

#### 3. Write a program to genrate an array of random integer numbers between 10 to 50 numbers of all possible shapes.

In [59]:
size = 20
a = np.random.randint(10,50,size)
for shape in findPossibleShapes(size):
    #print(shape)
    print("For shape::",shape)
    print(a.reshape(shape))
    print("#"*20)
    

For shape:: (5, 4)
[[46 17 16 41]
 [27 15 11 39]
 [27 35 39 20]
 [10 22 47 33]
 [37 37 44 15]]
####################
For shape:: (4, 5)
[[46 17 16 41 27]
 [15 11 39 27 35]
 [39 20 10 22 47]
 [33 37 37 44 15]]
####################
For shape:: (20, 1)
[[46]
 [17]
 [16]
 [41]
 [27]
 [15]
 [11]
 [39]
 [27]
 [35]
 [39]
 [20]
 [10]
 [22]
 [47]
 [33]
 [37]
 [37]
 [44]
 [15]]
####################
For shape:: (2, 10)
[[46 17 16 41 27 15 11 39 27 35]
 [39 20 10 22 47 33 37 37 44 15]]
####################
For shape:: (1, 20)
[[46 17 16 41 27 15 11 39 27 35 39 20 10 22 47 33 37 37 44 15]]
####################
For shape:: (10, 2)
[[46 17]
 [16 41]
 [27 15]
 [11 39]
 [27 35]
 [39 20]
 [10 22]
 [47 33]
 [37 37]
 [44 15]]
####################


#### 4. Write a program to generate an array of 100 equally spaced numbers between 1 to 7 numbers of possible shapes.

e.g : np.linspace(1,7,100) # from 1 to 7 100 numbers (equally spaced)

In [58]:
size = 14
a = np.linspace(1,7,size)
for shape in findPossibleShapes(size):
    #print(shape)
    print("For shape::",shape)
    print(a.reshape(shape))
    print("#"*20)
    

For shape:: (2, 7)
[[1.         1.46153846 1.92307692 2.38461538 2.84615385 3.30769231
  3.76923077]
 [4.23076923 4.69230769 5.15384615 5.61538462 6.07692308 6.53846154
  7.        ]]
####################
For shape:: (14, 1)
[[1.        ]
 [1.46153846]
 [1.92307692]
 [2.38461538]
 [2.84615385]
 [3.30769231]
 [3.76923077]
 [4.23076923]
 [4.69230769]
 [5.15384615]
 [5.61538462]
 [6.07692308]
 [6.53846154]
 [7.        ]]
####################
For shape:: (1, 14)
[[1.         1.46153846 1.92307692 2.38461538 2.84615385 3.30769231
  3.76923077 4.23076923 4.69230769 5.15384615 5.61538462 6.07692308
  6.53846154 7.        ]]
####################
For shape:: (7, 2)
[[1.         1.46153846]
 [1.92307692 2.38461538]
 [2.84615385 3.30769231]
 [3.76923077 4.23076923]
 [4.69230769 5.15384615]
 [5.61538462 6.07692308]
 [6.53846154 7.        ]]
####################


#### 5. Write a program to filter out all the numbers (generated from que.4) which is greater than 3.84 and less than 6.57.

In [62]:
size = 50
a = np.linspace(1,7,size)
print(a[(a>3.84) & (a<6.57)])

[3.93877551 4.06122449 4.18367347 4.30612245 4.42857143 4.55102041
 4.67346939 4.79591837 4.91836735 5.04081633 5.16326531 5.28571429
 5.40816327 5.53061224 5.65306122 5.7755102  5.89795918 6.02040816
 6.14285714 6.26530612 6.3877551  6.51020408]


#### 6. Write a program to replace first 3 numbers with 100 and middle 3'numbers with 200 and last 3 numbers with 300 in output of que.5

In [75]:
size = 50
a = np.linspace(1,7,size)
b = a[(a>3.84) & (a<6.57)]
# b[:3] = 100
middle_value = int((b.size)/2)
b[:3] = 0
b[middle_value-1:middle_value+2] = 200
b[-3:] = 300
print(b)

[  0.           0.           0.           4.30612245   4.42857143
   4.55102041   4.67346939   4.79591837   4.91836735   5.04081633
 200.         200.         200.           5.53061224   5.65306122
   5.7755102    5.89795918   6.02040816   6.14285714 300.
 300.         300.        ]


#### 7. Write a program to create a 5x5 matrix of random int numbers between 10 to 100 and
- replace upper triangle with zeros and print as a new matrix
- replace lower triangle with zeros and print as a new matrix

###### Already done in class

### Titanic Case Study
- Will be covered in case study session


#### 8. Continue exercise on Titanic dataset and do followings:
- Generate various plots for each features (columns) and tell your conclusion
- Perform various grouping of for any 2 colmuns and provide your conclusions by plotting them
- Perform various grouping of for any 3 colmuns and provide your conclusions by plotting them
- Perform various grouping of for any 4 colmuns and provide your conclusions by plotting them

Notes:
- provide proper labeling for the data points
- provide proper labeling for x and y axis
- provide proper title for each graph
- Do not create any sublpot more than 4x3 area (12 grapphs and one subplot)


